/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Events
         * @description specs/04-api-spec.md GET /audit-events — the "Screen 7: Audit" filterable event
         *     stream (specs/07-ui-spec.md). `object_type=document&object_id=<id>` is also how the
         *     per-document timeline view is built — there's no separate document-scoped endpoint.
         */
        get: operations["get_audit_events_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev Login */
        post: operations["dev_login_v1_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Prod path calls Cognito `sign_up` (email verification via Cognito hosted flow).
         *     Real Cognito wiring lands once a user pool exists — see infra/modules/cognito and
         *     specs/02-architecture.md ADR-7. For now this validates the shape of the contract.
         */
        post: operations["signup_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Candidate Route */
        patch: operations["patch_candidate_route_v1_candidates__candidate_id__patch"];
        trace?: never;
    };
    "/v1/certificates/{certificate_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Certificate Route
         * @description Deliberately public — no auth dependency. See migration 0004 for the RLS policy
         *     that makes this safe (declare-the-exact-id lookup, not a listing).
         */
        get: operations["verify_certificate_route_v1_certificates__certificate_id__verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description specs/01-product-spec.md US-16: "queue dashboards" — `assignee=me` is the "my
         *     queue" filter; a supervisor omits it (or passes another user's id) for "team queue".
         */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description specs/04-api-spec.md upload finalize: "creates document(s)". A ZIP is expanded
         *     into child documents (specs/05-redaction-pipeline.md Stage 1: "flatten one level;
         *     nested zips rejected") — bad entries are collected in `rejected` rather than failing
         *     the whole batch; a plain PDF still raises IntakeError (422) on validation failure,
         *     same as before ZIP support existed.
         */
        post: operations["upload_document_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_v1_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Document
         * @description specs/04-api-spec.md PATCH /documents/{id} — assign, due_date, request_id.
         */
        patch: operations["patch_document_v1_documents__doc_id__patch"];
        trace?: never;
    };
    "/v1/documents/{doc_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Candidate */
        post: operations["create_candidate_v1_documents__doc_id__candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/candidates:bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Update Route */
        post: operations["bulk_update_route_v1_documents__doc_id__candidates_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Document */
        post: operations["export_document_v1_documents__doc_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["get_manifest_v1_documents__doc_id__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pages */
        get: operations["list_pages_v1_documents__doc_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/pages/{page_no}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page Preview
         * @description specs/04-api-spec.md: "short-lived signed URL for rendered page image" in the real
         *     S3-backed design; served directly here since there's no S3/CDN to sign a URL against
         *     yet (app/storage/local.py). Still auth-gated the same way — org-scoped, not public.
         */
        get: operations["get_page_preview_v1_documents__doc_id__pages__page_no__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/review:approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Document Route
         * @description specs/04-api-spec.md: supervisor dual-approval — role-enforced here, not just
         *     reachable-but-ignored by reviewers (specs/10-build-plan.md Phase 3 AC).
         */
        post: operations["approve_document_route_v1_documents__doc_id__review_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/review:complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Review Route */
        post: operations["complete_review_route_v1_documents__doc_id__review_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/review:return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return Document Route */
        post: operations["return_document_route_v1_documents__doc_id__review_return_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/search-redact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Redact Route */
        post: operations["search_redact_route_v1_documents__doc_id__search_redact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exemption-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exemption Codes
         * @description specs/04-api-spec.md GET /exemption-codes — the org's own taxonomy (already cloned
         *     from the federal + state library at org creation, see exemption_service.py).
         */
        get: operations["list_exemption_codes_v1_exemption_codes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Export
         * @description specs/04-api-spec.md: "signed URL" in the real S3-backed design; served directly
         *     here for the same reason as page previews (app/storage/local.py) — still auth-gated
         *     and org-scoped via get_org_db, not public like certificate verification.
         */
        get: operations["download_export_v1_exports__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invite Route */
        post: operations["accept_invite_route_v1_invites__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Organization */
        post: operations["create_organization_v1_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Org */
        get: operations["get_current_org_v1_orgs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Current Org */
        patch: operations["update_current_org_v1_orgs_current_patch"];
        trace?: never;
    };
    "/v1/orgs/current/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite Member */
        post: operations["invite_member_v1_orgs_current_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/current/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Org Members */
        get: operations["list_org_members_v1_orgs_current_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/current/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Member */
        patch: operations["patch_member_v1_orgs_current_members__member_id__patch"];
        trace?: never;
    };
    "/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests Route */
        get: operations["list_requests_route_v1_requests_get"];
        put?: never;
        /** Create Request Route */
        post: operations["create_request_route_v1_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request Route */
        get: operations["get_request_route_v1_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Request Route */
        patch: operations["patch_request_route_v1_requests__request_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BBox */
        BBox: {
            /** H */
            h: number;
            /** W */
            w: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** BatchRejection */
        BatchRejection: {
            /** Filename */
            filename: string;
            /** Reason */
            reason: string;
        };
        /**
         * BatchUploadResult
         * @description specs/04-api-spec.md: upload finalize "creates document(s)" — always plural, since
         *     a ZIP batch (specs/05-redaction-pipeline.md Stage 1) may create many. A single-file
         *     upload is just the degenerate case: one document, zero rejections.
         */
        BatchUploadResult: {
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /** Rejected */
            rejected: components["schemas"]["BatchRejection"][];
        };
        /** Body_upload_document_v1_documents_post */
        Body_upload_document_v1_documents_post: {
            /** File */
            file: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** BulkUpdateRequest */
        BulkUpdateRequest: {
            /** Action */
            action: string;
            /** Candidate Ids */
            candidate_ids?: string[] | null;
            /** Confidence */
            confidence?: string | null;
            /** Exemption Code Id */
            exemption_code_id?: string | null;
            /** Recurrence Group Id */
            recurrence_group_id?: string | null;
        };
        /** BulkUpdateResponse */
        BulkUpdateResponse: {
            /** Updated */
            updated: components["schemas"]["CandidateOut"][];
        };
        /** CandidateCreate */
        CandidateCreate: {
            bbox: components["schemas"]["BBox"];
            /** Exemption Code Id */
            exemption_code_id: string;
            /** Note */
            note?: string | null;
            /** Page No */
            page_no: number;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Ai Justification */
            ai_justification?: string | null;
            bbox: components["schemas"]["BBox"];
            /** Confidence */
            confidence: string;
            /** Display Text */
            display_text: string;
            /** Exemption Code */
            exemption_code?: string | null;
            /** Exemption Code Id */
            exemption_code_id?: string | null;
            /** Id */
            id: string;
            /** Origin */
            origin: string;
            /** Page No */
            page_no: number;
            /** Recurrence Group Id */
            recurrence_group_id?: string | null;
            /** Source Rule Key */
            source_rule_key?: string | null;
            /** State */
            state: string;
        };
        /** CandidatePatch */
        CandidatePatch: {
            /** Ai Justification */
            ai_justification?: string | null;
            bbox?: components["schemas"]["BBox"] | null;
            /** Exemption Code Id */
            exemption_code_id?: string | null;
            /** Note */
            note?: string | null;
            /** State */
            state?: string | null;
        };
        /** CertificateVerifyResponse */
        CertificateVerifyResponse: {
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
            /** Valid */
            valid: boolean;
        };
        /**
         * DevLoginRequest
         * @description Local-only: mints a dev JWT for an existing (or newly created) user, standing in for
         *     the Cognito hosted login flow until a user pool exists.
         */
        DevLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Name
             * @default Dev User
             */
            name: string;
        };
        /** DocumentAssignPatch */
        DocumentAssignPatch: {
            /** Assignee Id */
            assignee_id?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Assignee Id */
            assignee_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due Date */
            due_date?: string | null;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Mime Type */
            mime_type: string;
            /** Ocr Used */
            ocr_used: boolean;
            /** Page Count */
            page_count?: number | null;
            /** Request Id */
            request_id?: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Uploaded By */
            uploaded_by: string;
        };
        /** ExemptionCodeOut */
        ExemptionCodeOut: {
            /** Code */
            code: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Statute Citation */
            statute_citation?: string | null;
        };
        /** ExportOut */
        ExportOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Doc Id */
            doc_id: string | null;
            /** Id */
            id: string;
            /** Integrity Check */
            integrity_check: {
                [key: string]: unknown;
            };
            /** Manifest Version */
            manifest_version: number;
            /** Sha256 */
            sha256: string;
            /** Type */
            type: string;
        };
        /** ExportRequest */
        ExportRequest: {
            /**
             * Types
             * @default [
             *       "clean_pdf",
             *       "exemption_log_csv",
             *       "certificate_pdf"
             *     ]
             */
            types: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteCreate */
        InviteCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Role */
            role: string;
        };
        /** InviteOut */
        InviteOut: {
            /** Accepted At */
            accepted_at?: string | null;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Id */
            id: string;
            /** Org Id */
            org_id: string;
            /** Role */
            role: string;
            /** Token */
            token?: string | null;
        };
        /** ManifestOut */
        ManifestOut: {
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
            /** Completeness */
            completeness: {
                [key: string]: unknown;
            };
            /** Doc Id */
            doc_id: string;
            /** Schema Version */
            schema_version: number;
            /** Version */
            version: number;
        };
        /** MemberOut */
        MemberOut: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Last Active At */
            last_active_at?: string | null;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** User Id */
            user_id: string;
        };
        /** MemberUpdate */
        MemberUpdate: {
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /** OrgCreate */
        OrgCreate: {
            /** Est Monthly Pages */
            est_monthly_pages?: number | null;
            /** Jurisdiction State */
            jurisdiction_state: string;
            /** Name */
            name: string;
            /** Org Type */
            org_type: string;
            /** Use Case */
            use_case?: string | null;
        };
        /** OrgOut */
        OrgOut: {
            /** Id */
            id: string;
            /** Jurisdiction State */
            jurisdiction_state: string;
            /** Name */
            name: string;
            /** Org Type */
            org_type: string;
            /** Plan */
            plan: string;
            /** Plan Status */
            plan_status: string;
            /**
             * Settings
             * @default {
             *       "default_rule_pack_ids": [],
             *       "dual_approval_required": false,
             *       "export_defaults": {
             *         "annotated_pdf": false,
             *         "clean_pdf": true,
             *         "exemption_log": true
             *       },
             *       "features": {},
             *       "retention_days_exports": 2555,
             *       "retention_days_uploads": 90
             *     }
             */
            settings: {
                [key: string]: unknown;
            };
            /** Slug */
            slug: string;
        };
        /** OrgSettingsUpdate */
        OrgSettingsUpdate: {
            /** Default Rule Pack Ids */
            default_rule_pack_ids?: string[] | null;
            /** Dual Approval Required */
            dual_approval_required?: boolean | null;
            /** Export Defaults */
            export_defaults?: {
                [key: string]: unknown;
            } | null;
            /** Retention Days Exports */
            retention_days_exports?: number | null;
            /** Retention Days Uploads */
            retention_days_uploads?: number | null;
        };
        /** PageOut */
        PageOut: {
            /** Has Text Layer */
            has_text_layer: boolean;
            /** Height */
            height: number;
            /** Page No */
            page_no: number;
            /** Rotation */
            rotation: number;
            /** Width */
            width: number;
        };
        /** RequestCreate */
        RequestCreate: {
            /** Assignee Id */
            assignee_id?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Reference No */
            reference_no?: string | null;
            /** Title */
            title: string;
        };
        /** RequestOut */
        RequestOut: {
            /** Assignee Id */
            assignee_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due Date */
            due_date?: string | null;
            /** Id */
            id: string;
            /** Reference No */
            reference_no?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** RequestPatch */
        RequestPatch: {
            /** Assignee Id */
            assignee_id?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
        };
        /** ReviewApprovalRequest */
        ReviewApprovalRequest: {
            /** Note */
            note?: string | null;
        };
        /** SearchRedactRequest */
        SearchRedactRequest: {
            /** Exemption Code Id */
            exemption_code_id: string;
            /**
             * Is Pattern
             * @default false
             */
            is_pattern: boolean;
            /** Page No */
            page_no?: number | null;
            /** Query */
            query: string;
            /**
             * Scope
             * @default document
             */
            scope: string;
        };
        /** SearchRedactResponse */
        SearchRedactResponse: {
            /** Created */
            created: components["schemas"]["CandidateOut"][];
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** SignupResponse */
        SignupResponse: {
            /** Email */
            email: string;
            /** User Id */
            user_id: string;
            /** Verification Required */
            verification_required: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_audit_events_v1_audit_events_get: {
        parameters: {
            query?: {
                actor_id?: string | null;
                action?: string | null;
                object_type?: string | null;
                object_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                format?: string;
            };
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dev_login_v1_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_candidate_route_v1_candidates__candidate_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_certificate_route_v1_certificates__certificate_id__verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query?: {
                status?: string | null;
                request_id?: string | null;
                /** @description "me" or a user id */
                assignee?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_v1_documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_document_v1_documents__doc_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentAssignPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_candidate_v1_documents__doc_id__candidates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_route_v1_documents__doc_id__candidates_bulk_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_v1_documents__doc_id__exports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_v1_documents__doc_id__manifest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pages_v1_documents__doc_id__pages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_preview_v1_documents__doc_id__pages__page_no__preview_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_document_route_v1_documents__doc_id__review_approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_review_route_v1_documents__doc_id__review_complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    return_document_route_v1_documents__doc_id__review_return_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_redact_route_v1_documents__doc_id__search_redact_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRedactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchRedactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exemption_codes_v1_exemption_codes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExemptionCodeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_v1_exports__export_id__download_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_route_v1_invites__token__accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_v1_orgs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_org_v1_orgs_current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_current_org_v1_orgs_current_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_member_v1_orgs_current_invites_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_org_members_v1_orgs_current_members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_member_v1_orgs_current_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_route_v1_requests_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_route_v1_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_route_v1_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_request_route_v1_requests__request_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
